# Generated by Django 4.1.5 on 2023-01-31 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='General_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=1024)),
                ('address', models.TextField(null=True)),
                ('landline_number', models.CharField(max_length=15, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True)),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nature_of_business', models.CharField(max_length=1024, null=True)),
                ('management', models.CharField(max_length=1024, null=True)),
                ('business_since', models.BigIntegerField(null=True)),
                ('product_line', models.CharField(max_length=1024, null=True)),
                ('business_ctgry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.business_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField()),
                ('contact_person', models.CharField(max_length=1024)),
                ('designation', models.CharField(max_length=1024, null=True)),
                ('mob_number', models.CharField(max_length=15, null=True)),
                ('insta_id', models.CharField(max_length=1024, null=True)),
                ('whatsapp_no', models.CharField(max_length=1024, null=True)),
                ('fb_id', models.CharField(max_length=1024, null=True)),
                ('front_office_assistant', models.CharField(max_length=1024, null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.general_information')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField()),
                ('trade_line', models.CharField(max_length=1024, null=True)),
                ('major_sector', models.CharField(max_length=1024, null=True)),
                ('existing_service_providers', models.CharField(max_length=1024, null=True)),
                ('crrnt_shipping_lines', models.CharField(max_length=1024, null=True)),
                ('business_volumes', models.CharField(max_length=1024, null=True)),
                ('special_remarks', models.CharField(max_length=1024, null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.general_information')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
