# Generated by Django 4.1.5 on 2023-02-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_information',
            name='created_by',
        ),
    ]
